### ISSUE TITLE
suspicious DOIs exist that are not redirected by https://doi.org

### ISSUE THREAD

**Issue by jhpoelen** [bat-literature/bat-literature.github.io#5]
In trying out all DOIs available in BatLit v0.1 , many redirected, however some did not. In total over 4.2k, and only about 28 DOIs causes a not found (404).

 count | status | description
 --- | --- | ---
4202 |  302 | temporary redirect
28 |  404 | not found
2  | 301 | permanent redirect 
1 |  000 | unknown

@ajacsherman @myrmoteras Please advise on how you'd like to prevent suspicious DOIs to propagate into Zenodo, possibly creating misdirected links .

404	https://doi.org/10.1007/s10393-017-1245-x;
404	https://doi.org/10.11694/pamj.supp.2015.22.1.6617
404	https://doi.org/10.32032/eid2206.160021
404	https://doi.org/10.1684/vir.2011.0418
404	https://doi.org/10.1371/currents.outbreaks.07992a87522e1f229c7cb023270a2af1
404	https://doi.org/10.1159/isbn.978-3-318-04030-2
404	https://doi.org/10.1644/09-MAMM-A-325.1.Key
404	https://doi.org/10.1002/path
404	https://doi.org/10.1182/blood-2014-02-514745.So
404	https://doi.org/10.1002/A
404	https://doi.org/10.4172/jgb.1000102
404	https://doi.org/10.1128/mBio.00164-10.Editor
404	https://doi.org/10.1371/journal.
000	pone.0200303
404	https://doi.org/10.1261/rna.046011.114.ing
404	https://doi.org/10.3201/eid1706.101355
404	https://doi.org/10.1007/s13398-014-0173-7.2
301	https://doi.org/10.3201/eid0703.010312
404	https://doi.org/10.1038/ncomms2343.Functional
404	https://doi.org/10.1016/j.immuni.2011.06.005.Skin-Resident
404	https://doi.org/10.1002/jcla
301	https://doi.org/10.1172/JCI200423215
404	https://doi.org/10.1128/AEM.70.5.2823
404	https://doi.org/10.1172/32108.of
404	https://doi.org/10.1124/pr.58.3.10.
404	https://doi.org/10.1101/gr.191049.115.Freely
404	https://doi.org/10.1002/pbc
404	https://doi.org/10.2307/2346101
404	https://doi.org/10.1128/CDLI.11.2.344
404	https://doi.org/10.1146/annurev.ecolsys.36.102003.152
404	https://doi.org/10.1124/jpet.105.095976.stic

**Comment by ajacsherman** [comment]
Some of these links (like https://doi.org/10.1007/s10393-017-1245-x) bring you to the data source. For the ones that are broken links, I would recommend omitting them. Donat?

**Comment by ajacsherman** [comment]
Can you find where https://doi.org/10.1684/vir.2011.0418 came from? The name of the paper, please?

**Comment by ajacsherman** [comment]
Would you provide where https://doi.org/10.1159/isbn.978-3-318-04030-2 came from? The citation please?

**Comment by ajacsherman** [comment]
Searching by the DOI is not producing results. Would you share whatever citations you have associated with these corrupt links?

**Comment by ajacsherman** [comment]
I was successful with https://doi.org/10.3201/eid0703.010312 [https://doi.org/10.3201%2Feid0703.010312] and https://doi.org/10.11694/pamj.supp.2015.22.1.6617 [https://doi.org/10.11604/pamj.supp.2015.22.1.6617] if you need a examples.

**Comment by myrmoteras** [comment]
@ajacsherman you can use https://refindit.org/ to search for DOI by entering eg the title etc.

**Comment by myrmoteras** [comment]
Would you provide where https://doi.org/10.1159/isbn.978-3-318-04030-2 has this https://karger.com/books/book/920/Virus-Infections-in-Bats found by searching via google

**Comment by ajacsherman** [comment]
I don't have the titles associated with the corrupt links

**Comment by jhpoelen** [comment]
> Can you find where https://doi.org/10.1684/vir.2011.0418 came from? The name of the paper, please?

This DOI was part of batlit v0.1, but is no longer present in batlit v0.2 . 

v0.1 - 

```
preston ls -anchor hash://sha256/6ba3d79cf1fd6349012cb4e527b6727b3e41e140489fa9c02f132e2cdd88d189\
 | grep hasVersion\
 | grep items?\
 | preston cat\
 | jq -c .[]\
 | grep "10.1684/vir.2011.0418"\
 | jq .
```

yielded:

```json
{
  "key": "UP3ETFVG",
  "version": 691,
  "library": {
    "type": "group",
    "id": 5435545,
    "name": "Bat Literature Project",
    "links": {
      "alternate": {
        "href": "https://www.zotero.org/groups/bat_literature_project",
        "type": "text/html"
      }
    }
  },
  "links": {
    "self": {
      "href": "https://api.zotero.org/groups/5435545/items/UP3ETFVG",
      "type": "application/json"
    },
    "alternate": {
      "href": "https://www.zotero.org/groups/bat_literature_project/items/UP3ETFVG",
      "type": "text/html"
    }
  },
  "meta": {
    "createdByUser": {
      "id": 6296343,
      "username": "deeannreeder",
      "name": "",
      "links": {
        "alternate": {
          "href": "https://www.zotero.org/deeannreeder",
          "type": "text/html"
        }
      }
    },
    "creatorSummary": "Talbi and Bourhy",
    "parsedDate": "2011-09-01",
    "numChildren": 1
  },
  "data": {
    "key": "UP3ETFVG",
    "version": 691,
    "itemType": "journalArticle",
    "title": "Dog rabies in Africa through genetic, spatial and temporal analysis of the isolates",
    "creators": [
      {
        "creatorType": "author",
        "firstName": "Chiraz",
        "lastName": "Talbi"
      },
      {
        "creatorType": "author",
        "firstName": "Herve",
        "lastName": "Bourhy"
      }
    ],
    "abstractNote": "This work illustrates the studies that have provided a better understanding of the genetic and geographic structure of dog rabies virus and the dynamics of rabies in domestic dogs in Africa, the second largest continent most affected by this disease. These investigations are a key element to control the disease and identify effective strategies for eliminating rabies locally, nationally as well as internationally and could drastically reduce human deaths caused by this disease. They also allow for the first time the investigation of the role of humans in the canine rabies virus spreading.",
    "publicationTitle": "Virologie",
    "volume": "15",
    "issue": "",
    "pages": "307-318",
    "date": "September 1, 2011",
    "series": "",
    "seriesTitle": "",
    "seriesText": "",
    "journalAbbreviation": "Virologie",
    "language": "",
    "DOI": "10.1684/vir.2011.0418",
    "ISSN": "",
    "shortTitle": "",
    "url": "",
    "accessDate": "",
    "archive": "",
    "archiveLocation": "",
    "libraryCatalog": "ResearchGate",
    "callNumber": "",
    "rights": "",
    "extra": "",
    "tags": [],
    "collections": [
      "DZKBQXJR"
    ],
    "relations": {
      "owl:sameAs": "http://zotero.org/groups/2719577/items/5VD54MKG"
    },
    "dateAdded": "2024-03-07T00:46:26Z",
    "dateModified": "2024-03-07T00:46:26Z"
  }
}
```

**Comment by jhpoelen** [comment]
> Would you provide where https://doi.org/10.1159/isbn.978-3-318-04030-2 came from? The citation please?

also exists in v0.1, but not in v0.2 

```bash
preston ls --anchor hash://sha256/6ba3d79cf1fd6349012cb4e527b6727b3e41e140489fa9c02f132e2cdd88d189 | grep hasVersion | grep items? | preston cat | jq -c .[] | grep "10.1159/isbn.978-3-318-04030-2" | jq .
```

yielded 

```json 
{
  "key": "GELIBCEP",
  "version": 608,
  "library": {
    "type": "group",
    "id": 5435545,
    "name": "Bat Literature Project",
    "links": {
      "alternate": {
        "href": "https://www.zotero.org/groups/bat_literature_project",
        "type": "text/html"
      }
    }
  },
  "links": {
    "self": {
      "href": "https://api.zotero.org/groups/5435545/items/GELIBCEP",
      "type": "application/json"
    },
    "alternate": {
      "href": "https://www.zotero.org/groups/bat_literature_project/items/GELIBCEP",
      "type": "text/html"
    }
  },
  "meta": {
    "createdByUser": {
      "id": 6296343,
      "username": "deeannreeder",
      "name": "",
      "links": {
        "alternate": {
          "href": "https://www.zotero.org/deeannreeder",
          "type": "text/html"
        }
      }
    },
    "creatorSummary": "Sulkin and Allen",
    "parsedDate": "1974",
    "numChildren": 0
  },
  "data": {
    "key": "GELIBCEP",
    "version": 608,
    "itemType": "journalArticle",
    "title": "Virus infections in bats",
    "creators": [
      {
        "creatorType": "author",
        "firstName": "S E",
        "lastName": "Sulkin"
      },
      {
        "creatorType": "author",
        "firstName": "R",
        "lastName": "Allen"
      }
    ],
    "abstractNote": "",
    "publicationTitle": "Monographs in virology",
    "volume": "8",
    "issue": "0",
    "pages": "1-103",
    "date": "1974",
    "series": "",
    "seriesTitle": "",
    "seriesText": "",
    "journalAbbreviation": "",
    "language": "",
    "DOI": "10.1159/isbn.978-3-318-04030-2",
    "ISSN": "0077-0965",
    "shortTitle": "",
    "url": "",
    "accessDate": "",
    "archive": "",
    "archiveLocation": "",
    "libraryCatalog": "",
    "callNumber": "",
    "rights": "",
    "extra": "PMID: 4367453\nISBN: 0077-0965 (Print) 0077-0965 (Linking)",
    "tags": [],
    "collections": [
      "DZKBQXJR"
    ],
    "relations": {
      "owl:sameAs": "http://zotero.org/groups/2446996/items/L845NLV5"
    },
    "dateAdded": "2024-03-06T17:28:04Z",
    "dateModified": "2024-03-06T17:28:04Z"
  }
}
```

however, no such record was found in v0.2. 

@ajacsherman curious to hear why this record no longer exists. . .

**Comment by jhpoelen** [comment]
> I was successful with https://doi.org/10.3201/eid0703.010312 [https://doi.org/10.3201%2Feid0703.010312] and https://doi.org/10.11694/pamj.supp.2015.22.1.6617 [https://doi.org/10.11604/pamj.supp.2015.22.1.6617] if you need a examples.

Hey @ajacsherman - thanks for sharing  your examples. 

From what I can tell, the suspicious DOIs that you could no longer find have been deleted from the Zotero group somehow.

This is consistent with finding `10.3201/eid0703.010312` in v0.2 as well as in v0.1.

```bash
preston ls --algo md5 --anchor hash://md5/be692b93a8edde4c4269be9e7d4ec1d7 | grep hasVersion | grep items? | preston cat | jq -c .[] | grep "10.3201/eid0703.010312" | jq . 
```

```json 
{
  "key": "UNPAII9M",
  "version": 405,
  "library": {
    "type": "group",
    "id": 5435545,
    "name": "Bat Literature Project",
    "links": {
      "alternate": {
        "href": "https://www.zotero.org/groups/bat_literature_project",
        "type": "text/html"
      }
    }
  },
  "links": {
    "self": {
      "href": "https://api.zotero.org/groups/5435545/items/UNPAII9M",
      "type": "application/json"
    },
    "alternate": {
      "href": "https://www.zotero.org/groups/bat_literature_project/items/UNPAII9M",
      "type": "text/html"
    },
    "attachment": {
      "href": "https://api.zotero.org/groups/5435545/items/6GC4864A",
      "type": "application/json",
      "attachmentType": "application/pdf",
      "attachmentSize": 76993
    }
  },
  "meta": {
    "createdByUser": {
      "id": 6296343,
      "username": "deeannreeder",
      "name": "",
      "links": {
        "alternate": {
          "href": "https://www.zotero.org/deeannreeder",
          "type": "text/html"
        }
      }
    },
    "creatorSummary": "Yob et al.",
    "parsedDate": "2001-06",
    "numChildren": 2
  },
  "data": {
    "key": "UNPAII9M",
    "version": 405,
    "itemType": "journalArticle",
    "title": "Nipah virus infection in bats (order Chiroptera) in peninsular Malaysia",
    "creators": [
      {
        "creatorType": "author",
        "firstName": "J. M.",
        "lastName": "Yob"
      },
      {
        "creatorType": "author",
        "firstName": "H.",
        "lastName": "Field"
      },
      {
        "creatorType": "author",
        "firstName": "A. M.",
        "lastName": "Rashdi"
      },
      {
        "creatorType": "author",
        "firstName": "C.",
        "lastName": "Morrissy"
      },
      {
        "creatorType": "author",
        "firstName": "B.",
        "lastName": "van der Heide"
      },
      {
        "creatorType": "author",
        "firstName": "P.",
        "lastName": "Rota"
      },
      {
        "creatorType": "author",
        "firstName": "A.",
        "lastName": "bin Adzhar"
      },
      {
        "creatorType": "author",
        "firstName": "J.",
        "lastName": "White"
      },
      {
        "creatorType": "author",
        "firstName": "P.",
        "lastName": "Daniels"
      },
      {
        "creatorType": "author",
        "firstName": "A.",
        "lastName": "Jamaluddin"
      },
      {
        "creatorType": "author",
        "firstName": "T.",
        "lastName": "Ksiazek"
      }
    ],
    "abstractNote": "Nipah virus, family Paramyxoviridae, caused disease in pigs and humans in peninsular Malaysia in 1998-99. Because Nipah virus appears closely related to Hendra virus, wildlife surveillance focused primarily on pteropid bats (suborder Megachiroptera), a natural host of Hendra virus in Australia. We collected 324 bats from 14 species on peninsular Malaysia. Neutralizing antibodies to Nipah virus were demonstrated in five species, suggesting widespread infection in bat populations in peninsular Malaysia.",
    "publicationTitle": "Emerging Infectious Diseases",
    "volume": "7",
    "issue": "3",
    "pages": "439-441",
    "date": "2001 May-Jun",
    "series": "",
    "seriesTitle": "",
    "seriesText": "",
    "journalAbbreviation": "Emerging Infect. Dis.",
    "language": "eng",
    "DOI": "10.3201/eid0703.010312",
    "ISSN": "1080-6040",
    "shortTitle": "",
    "url": "",
    "accessDate": "",
    "archive": "",
    "archiveLocation": "",
    "libraryCatalog": "PubMed",
    "callNumber": "",
    "rights": "",
    "extra": "PMID: 11384522\nPMCID: PMC2631791",
    "tags": [
      {
        "tag": "Animals",
        "type": 1
      },
      {
        "tag": "Antibodies, Viral",
        "type": 1
      },
      {
        "tag": "Chiroptera",
        "type": 1
      },
      {
        "tag": "Malaysia",
        "type": 1
      },
      {
        "tag": "Paramyxoviridae Infections",
        "type": 1
      },
      {
        "tag": "Paramyxovirinae",
        "type": 1
      },
      {
        "tag": "Seroepidemiologic Studies",
        "type": 1
      }
    ],
    "collections": [
      "DZKBQXJR"
    ],
    "relations": {
      "owl:sameAs": "http://zotero.org/groups/2446996/items/PAA8W8JH"
    },
    "dateAdded": "2024-03-06T17:26:09Z",
    "dateModified": "2024-03-06T17:26:09Z"
  }
}
```

**Comment by jhpoelen** [comment]
@ajacsherman so, as far as I can tell, if you can't find suspicious DOIs via Zotero, they have been either removed or updated.

Please note that doi `10.3201/eid0703.010312` made it to the list, because they had a 301 redirect instead of an expected 302 redirect. In other words, the doi url https://doi.org/10.3201/eid0703.010312 did redirect, only with an unusual redirect code 301.

Please holler if you'd like me to clarify by voice chat, happy to do so.

If you managed to get through all suspicious DOIs for this issue #5 , please feel free to close this issue.

Thanks for all your careful curation work.

**Comment by ajacsherman** [comment]
Good morning, I was replacing the DOIs I could find that were problematic. If I can't find the links you provided, I assume I have fixed them. Would you be able to run your report again with the corrupt DOIs as well as the citation associated with them? I should have kept a list of the ones I edited.

**Comment by jhpoelen** [comment]
@ajacsherman Thanks for your efforts. Does that also include the DOIs in #4 ? For some reason, the #4 reference to a DOI value associated with https://www.zotero.org/groups/5435545/bat_literature_project/items/2WK8GVE9 didn't change yet.

I'd be happy to re-run the check for the v0.3 release of batlit. Please let me know when would be a good time to run.

Alternatively, I can re-run the DOI check on batlit v0.2 and include the links to their associated Zotero records. 

Please let me know what works best for you.

**Comment by jhpoelen** [comment]
Here's a list of some of the 404 (not redirected DOIs) and their associated Zotero URLs. 

| suspicious doi | Zotero record URL |
| --- | --- |
| 10.1371/journal. pone.0200303 | https://www.zotero.org/groups/bat_literature_project/items/TE5RIWRU |
| 10.1007/s10393-017-1245-x; | https://www.zotero.org/groups/bat_literature_project/items/ZUHUHEHZ |
| 10.11694/pamj.supp.2015.22.1.6617 | https://www.zotero.org/groups/bat_literature_project/items/RDMWKGTG |
| 10.32032/eid2206.160021 | https://www.zotero.org/groups/bat_literature_project/items/4A7PYESU |
| 10.1371/currents.outbreaks.07992a87522e1f229c7cb023270a2af1 | https://www.zotero.org/groups/bat_literature_project/items/JT3HBLUQ |
| 10.1644/09-MAMM-A-325.1.Key | https://www.zotero.org/groups/bat_literature_project/items/LL5T2AXJ |
| 10.1002/jcla | https://www.zotero.org/groups/bat_literature_project/items/MMJLU8M9 |

**Comment by jhpoelen** [comment]
@ajacsherman happy to hear that the list of 404 DOIs and their associated Zotero links helped. 

There's the other list with likely malformed DOIs also in related issue at #4 . Did you include these in addition to the DOIs that did not resolve?

**Comment by jhpoelen** [comment]
We can always catch others in the next review. . . I am sure that many things have changed. I see these reviews like maintaining a garden . . . always weeds to be pulled, plants to be cared for, and new plants to be planted.

**Comment by ajacsherman** [comment]
I love this analogy!

**Comment by jhpoelen** [comment]
closing this issue to make room for fresh doi review.
